import { Suspense, lazy, useEffect, useState } from 'react'
import Head from 'next/head'
import Heading from 'components/heading'

import styles from 'styles/Home.module.css'

const Canvas = lazy(() => import('lazy/canvas'))
const Bokeh = lazy(() => import('scenes/bokeh'))

const Home = () => {
  const [bokehBg, setBokehBg] = useState()
  useEffect(() => {
    setBokehBg(
      window
        .getComputedStyle(document.documentElement)
        .getPropertyValue('--bokeh-bg')
        .trim()
    )
  }, [])

  const fallbackCanvas = <div className={styles.bokehPlaceholder} />

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Suspense fallback={fallbackCanvas}>
        <figure className={styles.bokehRendererContainer}>
          <Canvas dpr={[1, 10]} gl={{ alpha: false }} shadows camera={{ position: [0, -3.2, 40], fov: 12 }}>
            <color attach="background" args={[bokehBg]} />
            <Suspense fallback={null}>
              <Bokeh />
            </Suspense>
          </Canvas>
        </figure>
      </Suspense>

      <div className={styles.page}>
        <div className={styles.content}>
          <header className={styles.header}></header>
          <main className={styles.main}>
            <Heading className="test" as="h1">Sphinx of black quartz, judge my vow.</Heading>
            <Heading className="test" as="h2">Sphinx of black quartz, judge my vow.</Heading>
            <Heading className="test" as="h3">Sphinx of black quartz, judge my vow.</Heading>
            <Heading className="test" as="h4">Sphinx of black quartz, judge my vow.</Heading>
            <Heading className="test" as="h5">Sphinx of black quartz, judge my vow.</Heading>
            <Heading className="test" as="h6">Sphinx of black quartz, judge my vow.</Heading>
          </main>
          <footer className={styles.footer}></footer>
        </div>
      </div>
    </>
  )
}

export default Home
