import { Suspense, lazy } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { motion, useTransform } from 'framer-motion'

import Insignia from 'components/insignia'
import { Grid, Row } from 'components/grid'
import { Heading, Passage } from 'components/typography'
import MarkdownRenderer from 'components/markdown-renderer'
import Button from 'components/button'
import SkillsCloud from 'components/skills-cloud'

import { useDarkMode } from 'hooks/use-media-query'
import useMotionRate from 'hooks/use-motion-rate'
import useDreamscapeOpacity from 'hooks/use-dreamscape-opacity'
import cl from 'utils/classlist'

import Project from './projects/[slug].js'
import { getProjectsMeta } from 'generators/projects'

import aboutBlurb from 'blurbs/about.md'

import styles from 'styles/Home.module.css'

const ThreeWrapper = lazy(() => import('components/three-wrapper'))
const Dreamscape = lazy(() => import('scenes/dreamscape'))

const MotionHeading = motion(Heading)
const MotionPassage = motion(Passage)
const MotionButton = motion(Button)

const transition = {
  type: 'spring',
  damping: 40
}

const container = {
  show: {
    transition: {
      staggerChildren: 0.2
    }
  }
}

const item = {
  hidden: { y: 100, opacity: 0, transition },
  show: { y: 0, opacity: 1, transition }
}

const Home = ({ projectMetadata, activeProject }) => {
  const [scrollOpacity, initialFade] = useDreamscapeOpacity()
  const darkMode = useDarkMode()
  const motionRate = useMotionRate()
  const scheme = darkMode ? 'dark' : 'light'

  motionRate.set(Number(!activeProject))

  const placeholderStyle = {
    display: useTransform(initialFade, v => v < 1 ? 'block' : 'none')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.figure className={styles.dreamscape} style={{ opacity: scrollOpacity }}>
        <motion.div className={styles.placeholder} style={placeholderStyle}>
          <Image
            alt=""
            src={require(`scenes/dreamscape/loading-${scheme}.jpg`)}
            layout="fill"
            objectFit="cover"
            sizes="25vw"
          />
        </motion.div>
        <motion.div className={styles.rendererContainer} style={{ opacity: initialFade }}>
          <Suspense fallback={null}>
            <ThreeWrapper>
              <Suspense fallback={null}>
                <Dreamscape onFirstFrame={() => initialFade.set(1)} />
              </Suspense>
            </ThreeWrapper>
          </Suspense>
        </motion.div>
      </motion.figure>

      <div className={styles.page}>
        <div className={styles.content}>
          <header className={styles.header}></header>
          <main className={styles.main}>
            <section className={cl(styles.section, styles.hello)}>
              <div className={cl(styles.insignia, styles.top)}>
                <div className={styles.insigniaClip} />
              </div>
              <motion.div
                className={styles.introWrapper}
                variants={container}
                initial="hidden"
                animate="show"
              >
                <Grid>
                  <MotionHeading variants={item}>Hi there.</MotionHeading>
                  <div className={styles.intro}>
                    <MotionPassage as="p1" variants={item}>My name's <em>Ricky.</em></MotionPassage>
                    <MotionPassage as="p1" variants={item}>I do <em>design + code.</em></MotionPassage>
                    <MotionPassage as="p1" variants={item}><em>I'm looking for the next big thing. Right now.</em></MotionPassage>
                  </div>
                  <Row>
                    <MotionButton spans={[3]} variants={item}>Say Hi</MotionButton>
                    <MotionButton spans={[3]} variants={item}>See my CV</MotionButton>
                  </Row>
                </Grid>
              </motion.div>
            </section>

            <Grid className={styles.section}>
              <Heading as="h2">Here's what I can do.</Heading>
              <SkillsCloud />
            </Grid>

            <Grid className={[styles.section, styles.projects].join(' ')}>
              <Heading as="h2">Projects</Heading>
              <Row>
                {projectMetadata.map(summary => {
                  const { slug } = summary
                  const isExpanded = activeProject?.slug === slug
                  const passedDetails = isExpanded ? activeProject : summary
                  return (
                    <Project
                      key={passedDetails.slug}
                      spans={[passedDetails.metadata.grid || 4]}
                      data={passedDetails}
                      expanded={isExpanded}
                    />
                  )
                })}
              </Row>
            </Grid>

            <Grid className={[styles.section, styles.about].join(' ')}>
              <Heading as="h2">About Me</Heading>
              <Row>
                <figure className={styles.portrait} spans={[4]}>
                  <Image
                    layout="fill"
                    objectFit="cover"
                    sizes="(max-width: 640px) 94vw, 30vw"
                    src={require('public/images/me.png')}
                    alt="Portrait photo of Ricky Romero"
                  />
                </figure>
                <div spans={[8]}>
                  <MarkdownRenderer>{aboutBlurb}</MarkdownRenderer>
                </div>
              </Row>
            </Grid>

            <Grid className={[styles.section, styles.letsDoThis].join(' ')}>
              <Heading>Only 1 left in stock.</Heading>
              <Passage as="p1"><em>I'm looking for work,</em> but won't be for much longer.</Passage>
              <Passage as="p1">What do you want to build together?</Passage>
              <Row>
                <Button spans={[3]}>Say Hi</Button>
                <Button spans={[3]}>See my CV</Button>
              </Row>
            </Grid>
          </main>
          <footer className={styles.footer}></footer>
        </div>
      </div>

      <Insignia />
    </>
  )
}

const getStaticProps = async ({ params }) => {
  return {
    props: {
      projectMetadata: await getProjectsMeta()
    }
  }
}

export default Home
export { getStaticProps }
